[tool.poetry]
name = "equinox-rl"
version = "0.1.0"
description = ""
authors = ["Artur A. Galstyan <mail@arturgalstyan.dev>"]
readme = "README.md"
packages = [{include = "equinox_rl"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
equinox = "^0.10.2"
jax = "^0.4.8"
gymnasium = "^0.28.1"
nox = "^2022.11.21"
jaxtyping = "^0.2.14"
tensorflow-probability = "^0.19.0"
jaxlib = "^0.4.7"
tensorflow-macos = "^2.12.0"
rlax = "^0.1.5"
box2d = "2.3.2"
box2d-kengz = "^2.3.3"
pygame = "^2.3.0"
optuna = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
