[tool.poetry]
name = "equinox-rl"
version = "0.1.0"
description = ""
authors = ["Artur A. Galstyan <mail@arturgalstyan.dev>"]
readme = "README.md"
packages = [{include = "equinox_rl"}]

[tool.poetry.dependencies]
python = ">=3.10.10,<3.11"
equinox = "^0.10.2"
jax = "^0.4.7"
gymnasium = {extras = ["box2d"], version = "^0.28.1"}
nox = "^2022.11.21"
jaxtyping = "^0.2.14"
tensorflow-probability = "^0.19.0"
jaxlib = "^0.4.7"
tensorflow-macos = "^2.12.0"
optuna = "^3.1.1"
jupyter = "^1.0.0"
jupyterlab = "^3.6.3"
torch = "^2.0.1"
optax = "^0.1.5"
tqdm = "^4.65.0"
moviepy = "^1.0.3"
gym = "0.23.1"
chex = "^0.1.7"
matplotlib = "^3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["F722", "F821"]


